
import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.brand': 'Poshur Sheba',
    'nav.home': 'Home',
    'nav.market': 'Livestock Market',
    'nav.meatShop': 'Halal Meat Shop',
    'nav.farmers': 'Farmers',
    'nav.dairy': 'Dairy Products',
    'nav.vet': 'Veterinary',
    'nav.feed': 'Feed & Equipment',
    'nav.news': 'News',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.admin': 'Admin',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.cart': 'Cart',
    'nav.dashboard': 'Dashboard',
    'nav.search': 'Search',
    'nav.menu': 'Menu',

    // Home Page
    'home.title': 'CattleBes',
    'home.subtitle': 'Your Complete Livestock Service Platform',
    'home.description': 'Connecting farmers, buyers, and livestock professionals across Bangladesh',
    'home.hero.title': 'Smart Livestock Management',
    'home.hero.subtitle': 'Buy, sell, and manage your livestock with confidence',
    'home.hero.cta': 'Get Started',
    'home.hero.secondary': 'Learn More',

    // Services
    'services.title': 'Our Services',
    'services.market.title': 'Livestock Market',
    'services.market.description': 'Buy and sell quality livestock with verified sellers',
    'services.meat.title': 'Halal Meat Shop',
    'services.meat.description': 'Fresh halal meat products from trusted suppliers',
    'services.farmers.title': 'Farmers & Farms',
    'services.farmers.description': 'Connect with local farmers and farms',
    'services.dairy.title': 'Dairy Products',
    'services.dairy.description': 'Fresh milk and dairy items from local farms',
    'services.vet.title': 'Veterinary Services',
    'services.vet.description': 'Professional animal healthcare and consultation',
    'services.feed.title': 'Feed & Equipment',
    'services.feed.description': 'Quality feed and farming tools and equipment',

    // Market Page
    'market.title': 'Livestock Market',
    'market.description': 'Buy and sell quality livestock',
    'market.search.placeholder': 'Search cattle, breeds, or sellers...',
    'market.filter.title': 'Filters',
    'market.filter.type': 'Type',
    'market.filter.breed': 'Breed',
    'market.filter.price': 'Price Range',
    'market.filter.location': 'Location',
    'market.filter.age': 'Age',
    'market.filter.weight': 'Weight',
    'market.sort.newest': 'Newest First',
    'market.sort.price.low': 'Price: Low to High',
    'market.sort.price.high': 'Price: High to Low',
    'market.sort.views': 'Most Viewed',
    'market.add.listing': 'Add Listing',
    'market.view.details': 'View Details',
    'market.contact.seller': 'Contact Seller',
    'market.price': 'Price',
    'market.location': 'Location',
    'market.age': 'Age',
    'market.weight': 'Weight',
    'market.breed': 'Breed',
    'market.seller': 'Seller',
    'market.views': 'Views',

    // Meat Shop Page
    'meat.title': 'Halal Meat Shop',
    'meat.description': 'Fresh halal meat products',
    'meat.category.beef': 'Beef',
    'meat.category.mutton': 'Mutton',
    'meat.category.chicken': 'Chicken',
    'meat.category.buffalo': 'Buffalo',
    'meat.category.organ': 'Organ Meat',
    'meat.category.bone': 'Bone',
    'meat.halal.certified': 'Halal Certified',
    'meat.fresh': 'Fresh',
    'meat.frozen': 'Frozen',
    'meat.add.to.cart': 'Add to Cart',
    'meat.out.of.stock': 'Out of Stock',
    'meat.available': 'Available',

    // Farmers Page
    'farmers.title': 'Farmers & Farms',
    'farmers.description': 'Connect with local farmers',
    'farmers.search.placeholder': 'Search farmers, farms, or locations...',
    'farmers.filter.speciality': 'Speciality',
    'farmers.filter.experience': 'Experience',
    'farmers.filter.location': 'Location',
    'farmers.contact': 'Contact',
    'farmers.farm.name': 'Farm Name',
    'farmers.speciality': 'Speciality',
    'farmers.experience': 'Experience',
    'farmers.location': 'Location',
    'farmers.rating': 'Rating',
    'farmers.total.sales': 'Total Sales',

    // Dairy Page
    'dairy.title': 'Dairy Products',
    'dairy.description': 'Fresh milk and dairy items',
    'dairy.category.milk': 'Milk',
    'dairy.category.yogurt': 'Yogurt',
    'dairy.category.cheese': 'Cheese',
    'dairy.category.butter': 'Butter',
    'dairy.category.ghee': 'Ghee',
    'dairy.category.cream': 'Cream',
    'dairy.fresh': 'Fresh',
    'dairy.pasteurized': 'Pasteurized',
    'dairy.organic': 'Organic',

    // Veterinary Page
    'vet.title': 'Veterinary Services',
    'vet.description': 'Professional animal healthcare',
    'vet.search.placeholder': 'Search veterinarians, specializations...',
    'vet.filter.specialization': 'Specialization',
    'vet.filter.availability': 'Availability',
    'vet.filter.location': 'Location',
    'vet.clinic.name': 'Clinic Name',
    'vet.specialization': 'Specialization',
    'vet.license': 'License Number',
    'vet.availability': 'Availability',
    'vet.rating': 'Rating',
    'vet.book.appointment': 'Book Appointment',
    'vet.emergency': 'Emergency Service',
    'vet.contact.all': 'Contact All Veterinarians',
    'vet.contact.title': 'Contact Veterinarians',
    'vet.contact.description': 'Connect with professional veterinarians for your livestock health needs',
    'vet.contact.no.available': 'No veterinarians available',
    'vet.contact.check.later': 'Check back later for veterinarian listings',
    'vet.contact.book.appointment': 'Book Appointment',
    'vet.contact.emergency.contact': 'Emergency Contact',
    'vet.contact.appointment.message': 'Hello Dr. {name}! I would like to book an appointment for my livestock. Please let me know your available time slots.',
    'vet.contact.emergency.message': 'EMERGENCY: Hello Dr. {name}! I have an emergency with my livestock and need immediate assistance. Please help!',

    // Feed & Equipment Page
    'feed.title': 'Feed & Equipment',
    'feed.description': 'Quality feed and farming tools',
    'feed.category.feed': 'Feed',
    'feed.category.supplement': 'Supplement',
    'feed.category.seed': 'Seed',
    'feed.category.equipment': 'Equipment',
    'feed.category.tool': 'Tool',
    'feed.category.machine': 'Machine',
    'feed.brand': 'Brand',
    'feed.weight': 'Weight',
    'feed.unit': 'Unit',

    // News Page
    'news.title': 'Articles & News',
    'news.description': 'Latest livestock industry updates',
    'news.category.health': 'Health',
    'news.category.production': 'Production',
    'news.category.technology': 'Technology',
    'news.category.sustainability': 'Sustainability',
    'news.category.market': 'Market',
    'news.category.government': 'Government',
    'news.read.more': 'Read More',
    'news.published': 'Published',
    'news.author': 'Author',
    'news.read.time': 'Read Time',
    'news.refresh': 'Refresh News',
    'news.last.updated': 'Last Updated',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.description': 'Get in touch with us',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.required': 'Required',
    'contact.info.address': 'Address',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Business Hours',
    'contact.success': 'Message sent successfully!',
    'contact.error': 'Failed to send message. Please try again.',

    // Authentication
    'auth.login.title': 'Welcome Back',
    'auth.login.subtitle': 'Sign in to your account',
    'auth.register.title': 'Create Account',
    'auth.register.subtitle': 'Join our livestock community',
    'auth.form.email': 'Email Address',
    'auth.form.password': 'Password',
    'auth.form.confirmPassword': 'Confirm Password',
    'auth.form.name': 'Full Name',
    'auth.form.phone': 'Phone Number',
    'auth.form.userType': 'User Type',
    'auth.form.farmName': 'Farm Name',
    'auth.form.location': 'Location',
    'auth.form.speciality': 'Speciality',
    'auth.form.experience': 'Experience',
    'auth.form.description': 'Description',
    'auth.form.clinicName': 'Clinic Name',
    'auth.form.specialization': 'Specialization',
    'auth.form.licenseNumber': 'License Number',
    'auth.form.availability': 'Availability',
    'auth.form.shopName': 'Shop Name',

    'auth.form.address': 'Address',
    'auth.userType.farmer': 'Farmer',
    'auth.userType.buyer': 'Buyer',
    'auth.userType.veterinarian': 'Veterinarian',
    'auth.userType.seller': 'Seller',
    'auth.login.button': 'Sign In',
    'auth.register.button': 'Create Account',
    'auth.forgot.password': 'Forgot Password?',
    'auth.no.account': "Don't have an account?",
    'auth.have.account': 'Already have an account?',
    'auth.login.link': 'Sign In',
    'auth.register.link': 'Sign Up',

    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Manage users, content, and monitor platform activity',
    'admin.stats.totalUsers': 'Total Users',
    'admin.stats.cattleListings': 'Cattle Listings',
    'admin.stats.products': 'Products',
    'admin.stats.ratings': 'Ratings',
    'admin.content.management': 'Content Management',
    'admin.users': 'Users',
    'admin.cattle': 'Cattle',
    'admin.products': 'Products',
    'admin.news': 'News',
    'admin.ratings': 'Ratings',
    'admin.delete': 'Delete',
    'admin.edit': 'Edit',
    'admin.view': 'View',
    'admin.confirm.delete': 'Are you sure you want to delete this item?',
    'admin.delete.success': 'Item deleted successfully',
    'admin.delete.error': 'Failed to delete item',

    // Common
    'common.loading': 'Loading...',

    // Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.items': 'Items',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.clear': 'Clear Cart',
    'cart.remove': 'Remove',
    'cart.quantity': 'Quantity',
    'cart.price': 'Price',
    'cart.subtotal': 'Subtotal',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.add': 'Add',
    'common.update': 'Update',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.clear': 'Clear',
    'common.apply': 'Apply',
    'common.reset': 'Reset',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.more': 'More',
    'common.less': 'Less',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.confirm': 'Confirm',
    'common.dismiss': 'Dismiss',
    'common.retry': 'Retry',
    'common.refresh': 'Refresh',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.print': 'Print',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.paste': 'Paste',
    'common.cut': 'Cut',
    'common.select': 'Select',
    'common.deselect': 'Deselect',
    'common.selectAll': 'Select All',
    'common.deselectAll': 'Deselect All',
    'common.invert': 'Invert Selection',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.summary': 'Summary',
    'common.description': 'Description',
    'common.title': 'Title',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.location': 'Location',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.type': 'Type',
    'common.category': 'Category',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.tax': 'Tax',
    'common.discount': 'Discount',
    'common.shipping': 'Shipping',
    'common.grandTotal': 'Grand Total',
    'common.currency': '৳',
    'common.currency.symbol': '৳',
    'common.currency.name': 'Bangladeshi Taka',
    'common.currency.code': 'BDT',

    // Premium Features
    'premium.title': 'CattleBase Premium Management',
    'premium.description': 'Advanced features for modern livestock management',
    'premium.feature.videoAuction': 'Live Video Auction System',
    'premium.feature.verifiedBadges': 'Verified Farm Badges',
    'premium.feature.aiPricing': 'AI-based Cattle Price Estimation',
    'premium.feature.mobileApp': 'Mobile App Integration',
    'premium.feature.paymentGateway': 'Payment Gateway (SSLCommerz)',
    'premium.feature.gpsLocator': 'GPS Farm Locator',
    'premium.feature.description.videoAuction': 'Real-time bidding with HD video streaming',
    'premium.feature.description.verifiedBadges': 'Trust certification for quality assurance',
    'premium.feature.description.aiPricing': 'Smart pricing using machine learning',
    'premium.feature.description.mobileApp': 'iOS & Android app connectivity',
    'premium.feature.description.paymentGateway': 'Secure online payment processing',
    'premium.feature.description.gpsLocator': 'Real-time farm location tracking',

    // Not Found
    'notFound.title': 'Page Not Found',
    'notFound.description': 'The page you are looking for does not exist.',
    'notFound.backHome': 'Back to Home',
  },
  bn: {
    // Navigation
    'nav.home': 'হোম',
    'nav.market': 'পশুর বাজার',
    'nav.meat': 'হালাল মাংসের দোকান',
    'nav.farmers': 'কৃষকগণ',
    'nav.dairy': 'দুগ্ধজাত পণ্য',
    'nav.vet': 'পশু চিকিৎসা',
    'nav.feed': 'খাদ্য ও সরঞ্জাম',
    'nav.news': 'সংবাদ',
    'nav.contact': 'যোগাযোগ',
    'nav.login': 'লগইন',
    'nav.register': 'নিবন্ধন',
    'nav.admin': 'অ্যাডমিন',
    'nav.profile': 'প্রোফাইল',
    'nav.logout': 'লগআউট',
    'nav.cart': 'কার্ট',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.search': 'অনুসন্ধান',
    'nav.menu': 'মেনু',

    // Home Page
    'home.title': 'ক্যাটেলবেস',
    'home.subtitle': 'আপনার সম্পূর্ণ পশুসেবা প্ল্যাটফর্ম',
    'home.description': 'বাংলাদেশ জুড়ে কৃষক, ক্রেতা এবং পশুপালন পেশাদারদের সংযুক্ত করা',
    'home.hero.title': 'স্মার্ট পশুপালন ব্যবস্থাপনা',
    'home.hero.subtitle': 'আত্মবিশ্বাসের সাথে আপনার পশু কিনুন, বিক্রি করুন এবং পরিচালনা করুন',
    'home.hero.cta': 'শুরু করুন',
    'home.hero.secondary': 'আরও জানুন',

    // Services
    'services.title': 'আমাদের সেবাসমূহ',
    'services.market.title': 'পশুর বাজার',
    'services.market.description': 'যাচাইকৃত বিক্রেতাদের কাছ থেকে মানসম্পন্ন পশু কিনুন ও বিক্রি করুন',
    'services.meat.title': 'হালাল মাংসের দোকান',
    'services.meat.description': 'বিশ্বস্ত সরবরাহকারীদের কাছ থেকে তাজা হালাল মাংসের পণ্য',
    'services.farmers.title': 'কৃষক ও খামার',
    'services.farmers.description': 'স্থানীয় কৃষক ও খামারের সাথে যোগাযোগ',
    'services.dairy.title': 'দুগ্ধজাত পণ্য',
    'services.dairy.description': 'স্থানীয় খামার থেকে তাজা দুধ ও দুগ্ধজাত পণ্য',
    'services.vet.title': 'পশু চিকিৎসা সেবা',
    'services.vet.description': 'পেশাদার পশু স্বাস্থ্যসেবা ও পরামর্শ',
    'services.feed.title': 'খাদ্য ও সরঞ্জাম',
    'services.feed.description': 'মানসম্পন্ন খাদ্য ও কৃষি সরঞ্জাম',

    // Market Page
    'market.title': 'পশুর বাজার',
    'market.description': 'মানসম্পন্ন পশু কিনুন ও বিক্রি করুন',
    'market.search.placeholder': 'গবাদি পশু, জাত বা বিক্রেতা অনুসন্ধান করুন...',
    'market.filter.title': 'ফিল্টার',
    'market.filter.type': 'ধরন',
    'market.filter.breed': 'জাত',
    'market.filter.price': 'মূল্য পরিসীমা',
    'market.filter.location': 'অবস্থান',
    'market.filter.age': 'বয়স',
    'market.filter.weight': 'ওজন',
    'market.sort.newest': 'নতুন প্রথম',
    'market.sort.price.low': 'মূল্য: কম থেকে বেশি',
    'market.sort.price.high': 'মূল্য: বেশি থেকে কম',
    'market.sort.views': 'সবচেয়ে দেখা',
    'market.add.listing': 'তালিকা যোগ করুন',
    'market.view.details': 'বিস্তারিত দেখুন',
    'market.contact.seller': 'বিক্রেতার সাথে যোগাযোগ',
    'market.price': 'মূল্য',
    'market.location': 'অবস্থান',
    'market.age': 'বয়স',
    'market.weight': 'ওজন',
    'market.breed': 'জাত',
    'market.seller': 'বিক্রেতা',
    'market.views': 'দেখা',

    // Meat Shop Page
    'meat.title': 'হালাল মাংসের দোকান',
    'meat.description': 'তাজা হালাল মাংসের পণ্য',
    'meat.category.beef': 'গরুর মাংস',
    'meat.category.mutton': 'ছাগলের মাংস',
    'meat.category.chicken': 'মুরগির মাংস',
    'meat.category.buffalo': 'মহিষের মাংস',
    'meat.category.organ': 'অঙ্গের মাংস',
    'meat.category.bone': 'হাড়',
    'meat.halal.certified': 'হালাল সার্টিফাইড',
    'meat.fresh': 'তাজা',
    'meat.frozen': 'হিমায়িত',
    'meat.add.to.cart': 'কার্টে যোগ করুন',
    'meat.out.of.stock': 'স্টক নেই',
    'meat.available': 'উপলব্ধ',

    // Farmers Page
    'farmers.title': 'কৃষক ও খামার',
    'farmers.description': 'স্থানীয় কৃষকদের সাথে যোগাযোগ',
    'farmers.search.placeholder': 'কৃষক, খামার বা অবস্থান অনুসন্ধান করুন...',
    'farmers.filter.speciality': 'বিশেষজ্ঞতা',
    'farmers.filter.experience': 'অভিজ্ঞতা',
    'farmers.filter.location': 'অবস্থান',
    'farmers.contact': 'যোগাযোগ',
    'farmers.farm.name': 'খামারের নাম',
    'farmers.speciality': 'বিশেষজ্ঞতা',
    'farmers.experience': 'অভিজ্ঞতা',
    'farmers.location': 'অবস্থান',
    'farmers.rating': 'রেটিং',
    'farmers.total.sales': 'মোট বিক্রয়',

    // Dairy Page
    'dairy.title': 'দুগ্ধজাত পণ্য',
    'dairy.description': 'তাজা দুধ ও দুগ্ধজাত পণ্য',
    'dairy.category.milk': 'দুধ',
    'dairy.category.yogurt': 'দই',
    'dairy.category.cheese': 'পনির',
    'dairy.category.butter': 'মাখন',
    'dairy.category.ghee': 'ঘি',
    'dairy.category.cream': 'ক্রিম',
    'dairy.fresh': 'তাজা',
    'dairy.pasteurized': 'পাস্তুরাইজড',
    'dairy.organic': 'জৈব',

    // Veterinary Page
    'vet.title': 'পশু চিকিৎসা সেবা',
    'vet.description': 'পেশাদার পশু স্বাস্থ্যসেবা',
    'vet.search.placeholder': 'পশুচিকিৎসক, বিশেষজ্ঞতা অনুসন্ধান করুন...',
    'vet.filter.specialization': 'বিশেষজ্ঞতা',
    'vet.filter.availability': 'উপলব্ধতা',
    'vet.filter.location': 'অবস্থান',
    'vet.clinic.name': 'ক্লিনিকের নাম',
    'vet.specialization': 'বিশেষজ্ঞতা',
    'vet.license': 'লাইসেন্স নম্বর',
    'vet.availability': 'উপলব্ধতা',
    'vet.rating': 'রেটিং',
    'vet.book.appointment': 'অ্যাপয়েন্টমেন্ট বুক করুন',
    'vet.emergency': 'জরুরি সেবা',

    // Feed & Equipment Page
    'feed.title': 'খাদ্য ও সরঞ্জাম',
    'feed.description': 'মানসম্পন্ন খাদ্য ও কৃষি সরঞ্জাম',
    'feed.category.feed': 'খাদ্য',
    'feed.category.supplement': 'সম্পূরক',
    'feed.category.seed': 'বীজ',
    'feed.category.equipment': 'সরঞ্জাম',
    'feed.category.tool': 'যন্ত্রপাতি',
    'feed.category.machine': 'মেশিন',
    'feed.brand': 'ব্র্যান্ড',
    'feed.weight': 'ওজন',
    'feed.unit': 'একক',

    // News Page
    'news.title': 'নিবন্ধ ও সংবাদ',
    'news.description': 'পশুপালন শিল্পের সর্বশেষ আপডেট',
    'news.category.health': 'স্বাস্থ্য',
    'news.category.production': 'উৎপাদন',
    'news.category.technology': 'প্রযুক্তি',
    'news.category.sustainability': 'টেকসইতা',
    'news.category.market': 'বাজার',
    'news.category.government': 'সরকার',
    'news.read.more': 'আরও পড়ুন',
    'news.published': 'প্রকাশিত',
    'news.author': 'লেখক',
    'news.read.time': 'পঠন সময়',
    'news.refresh': 'সংবাদ রিফ্রেশ করুন',
    'news.last.updated': 'সর্বশেষ আপডেট',

    // Contact Page
    'contact.title': 'যোগাযোগ করুন',
    'contact.description': 'আমাদের সাথে যোগাযোগ করুন',
    'contact.form.name': 'পূর্ণ নাম',
    'contact.form.email': 'ইমেইল ঠিকানা',
    'contact.form.phone': 'ফোন নম্বর',
    'contact.form.subject': 'বিষয়',
    'contact.form.message': 'বার্তা',
    'contact.form.submit': 'বার্তা পাঠান',
    'contact.form.required': 'প্রয়োজনীয়',
    'contact.info.address': 'ঠিকানা',
    'contact.info.phone': 'ফোন',
    'contact.info.email': 'ইমেইল',
    'contact.info.hours': 'ব্যবসার সময়',
    'contact.success': 'বার্তা সফলভাবে পাঠানো হয়েছে!',
    'contact.error': 'বার্তা পাঠানো ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',

    // Authentication
    'auth.login.title': 'আবার স্বাগতম',
    'auth.login.subtitle': 'আপনার অ্যাকাউন্টে সাইন ইন করুন',
    'auth.register.title': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.register.subtitle': 'আমাদের পশুপালন সম্প্রদায়ে যোগ দিন',
    'auth.form.email': 'ইমেইল ঠিকানা',
    'auth.form.password': 'পাসওয়ার্ড',
    'auth.form.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
    'auth.form.name': 'পূর্ণ নাম',
    'auth.form.phone': 'ফোন নম্বর',
    'auth.form.userType': 'ব্যবহারকারীর ধরন',
    'auth.form.farmName': 'খামারের নাম',
    'auth.form.location': 'অবস্থান',
    'auth.form.speciality': 'বিশেষজ্ঞতা',
    'auth.form.experience': 'অভিজ্ঞতা',
    'auth.form.description': 'বিবরণ',
    'auth.form.clinicName': 'ক্লিনিকের নাম',
    'auth.form.specialization': 'বিশেষজ্ঞতা',
    'auth.form.licenseNumber': 'লাইসেন্স নম্বর',
    'auth.form.availability': 'উপলব্ধতা',
    'auth.form.shopName': 'দোকানের নাম',

    'auth.form.address': 'ঠিকানা',
    'auth.userType.farmer': 'কৃষক',
    'auth.userType.buyer': 'ক্রেতা',
    'auth.userType.veterinarian': 'পশুচিকিৎসক',
    'auth.userType.seller': 'মাংস বিক্রেতা',
    'auth.login.button': 'সাইন ইন',
    'auth.register.button': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.forgot.password': 'পাসওয়ার্ড ভুলে গেছেন?',
    'auth.no.account': 'অ্যাকাউন্ট নেই?',
    'auth.have.account': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    'auth.login.link': 'সাইন ইন',
    'auth.register.link': 'সাইন আপ',

    // Admin Dashboard
    'admin.title': 'অ্যাডমিন ড্যাশবোর্ড',
    'admin.subtitle': 'ব্যবহারকারী, বিষয়বস্তু পরিচালনা করুন এবং প্ল্যাটফর্ম কার্যকলাপ পর্যবেক্ষণ করুন',
    'admin.stats.totalUsers': 'মোট ব্যবহারকারী',
    'admin.stats.cattleListings': 'গবাদি পশুর তালিকা',
    'admin.stats.products': 'পণ্য',
    'admin.stats.ratings': 'রেটিং',
    'admin.content.management': 'বিষয়বস্তু পরিচালনা',
    'admin.users': 'ব্যবহারকারী',
    'admin.cattle': 'গবাদি পশু',
    'admin.products': 'পণ্য',
    'admin.news': 'সংবাদ',
    'admin.ratings': 'রেটিং',
    'admin.delete': 'মুছুন',
    'admin.edit': 'সম্পাদনা',
    'admin.view': 'দেখুন',
    'admin.confirm.delete': 'আপনি কি নিশ্চিত যে আপনি এই আইটেমটি মুছতে চান?',
    'admin.delete.success': 'আইটেম সফলভাবে মুছে ফেলা হয়েছে',
    'admin.delete.error': 'আইটেম মুছতে ব্যর্থ হয়েছে',

    // Cart
    'cart.title': 'শপিং কার্ট',
    'cart.empty': 'আপনার কার্ট খালি',
    'cart.items': 'আইটেম',
    'cart.total': 'মোট',
    'cart.checkout': 'চেকআউট',
    'cart.clear': 'কার্ট খালি করুন',
    'cart.remove': 'সরান',
    'cart.quantity': 'পরিমাণ',
    'cart.price': 'মূল্য',
    'cart.subtotal': 'উপমোট',

    // Common
    'common.loading': 'লোড হচ্ছে...',
    'common.error': 'ত্রুটি',
    'common.success': 'সফল',
    'common.cancel': 'বাতিল',
    'common.save': 'সংরক্ষণ',
    'common.edit': 'সম্পাদনা',
    'common.delete': 'মুছুন',
    'common.view': 'দেখুন',
    'common.add': 'যোগ করুন',
    'common.update': 'আপডেট',
    'common.search': 'অনুসন্ধান',
    'common.filter': 'ফিল্টার',
    'common.sort': 'সাজান',
    'common.clear': 'মুছুন',
    'common.apply': 'প্রয়োগ করুন',
    'common.reset': 'রিসেট',
    'common.close': 'বন্ধ করুন',
    'common.back': 'পিছনে',
    'common.next': 'পরবর্তী',
    'common.previous': 'পূর্ববর্তী',
    'common.more': 'আরও',
    'common.less': 'কম',
    'common.all': 'সব',
    'common.none': 'কোনটি নয়',
    'common.yes': 'হ্যাঁ',
    'common.no': 'না',
    'common.ok': 'ঠিক আছে',
    'common.confirm': 'নিশ্চিত করুন',
    'common.dismiss': 'খারিজ করুন',
    'common.retry': 'পুনরায় চেষ্টা করুন',
    'common.refresh': 'রিফ্রেশ',
    'common.download': 'ডাউনলোড',
    'common.upload': 'আপলোড',
    'common.export': 'এক্সপোর্ট',
    'common.import': 'ইমপোর্ট',
    'common.print': 'প্রিন্ট',
    'common.share': 'শেয়ার',
    'common.copy': 'কপি',
    'common.paste': 'পেস্ট',
    'common.cut': 'কাট',
    'common.select': 'নির্বাচন করুন',
    'common.deselect': 'নির্বাচন বাতিল করুন',
    'common.selectAll': 'সব নির্বাচন করুন',
    'common.deselectAll': 'সব নির্বাচন বাতিল করুন',
    'common.invert': 'নির্বাচন উল্টান',
    'common.actions': 'কর্ম',
    'common.details': 'বিস্তারিত',
    'common.summary': 'সারসংক্ষেপ',
    'common.description': 'বিবরণ',
    'common.title': 'শিরোনাম',
    'common.name': 'নাম',
    'common.email': 'ইমেইল',
    'common.phone': 'ফোন',
    'common.address': 'ঠিকানা',
    'common.location': 'অবস্থান',
    'common.date': 'তারিখ',
    'common.time': 'সময়',
    'common.status': 'অবস্থা',
    'common.type': 'ধরন',
    'common.category': 'বিভাগ',
    'common.price': 'মূল্য',
    'common.quantity': 'পরিমাণ',
    'common.total': 'মোট',
    'common.subtotal': 'উপমোট',
    'common.tax': 'কর',
    'common.discount': 'ছাড়',
    'common.shipping': 'শিপিং',
    'common.grandTotal': 'মোট মূল্য',
    'common.currency': '৳',
    'common.currency.symbol': '৳',
    'common.currency.name': 'বাংলাদেশি টাকা',
    'common.currency.code': 'বিডিটি',

    // Premium Features
    'premium.title': 'ক্যাটেলবেস প্রিমিয়াম ব্যবস্থাপনা',
    'premium.description': 'আধুনিক পশুপালন ব্যবস্থাপনার জন্য উন্নত বৈশিষ্ট্য',
    'premium.feature.videoAuction': 'লাইভ ভিডিও নিলাম সিস্টেম',
    'premium.feature.verifiedBadges': 'যাচাইকৃত খামার ব্যাজ',
    'premium.feature.aiPricing': 'এআই-ভিত্তিক গবাদি পশুর মূল্য নির্ধারণ',
    'premium.feature.mobileApp': 'মোবাইল অ্যাপ ইন্টিগ্রেশন',
    'premium.feature.paymentGateway': 'পেমেন্ট গেটওয়ে (এসএসএলকমার্জ)',
    'premium.feature.gpsLocator': 'জিপিএস খামার লোকেটর',
    'premium.feature.description.videoAuction': 'এইচডি ভিডিও স্ট্রিমিং সহ রিয়েল-টাইম বিডিং',
    'premium.feature.description.verifiedBadges': 'মান নিশ্চিতকরণের জন্য বিশ্বাস সার্টিফিকেশন',
    'premium.feature.description.aiPricing': 'মেশিন লার্নিং ব্যবহার করে স্মার্ট মূল্য নির্ধারণ',
    'premium.feature.description.mobileApp': 'আইওএস এবং অ্যান্ড্রয়েড অ্যাপ সংযোগ',
    'premium.feature.description.paymentGateway': 'নিরাপদ অনলাইন পেমেন্ট প্রক্রিয়াকরণ',
    'premium.feature.description.gpsLocator': 'রিয়েল-টাইম খামার অবস্থান ট্র্যাকিং',

    // Not Found
    'notFound.title': 'পৃষ্ঠা পাওয়া যায়নি',
    'notFound.description': 'আপনি যে পৃষ্ঠাটি খুঁজছেন তা বিদ্যমান নেই।',
    'notFound.backHome': 'হোমে ফিরে যান',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'bn' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      currentLanguage: language,
      setLanguage, 
      toggleLanguage,
      t 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
